services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stockstream-backend
    ports:
      - "8000:8000"
    environment:
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
    networks:
      - stockstream-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stockstream-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - stockstream-network
    restart: unless-stopped

networks:
  stockstream-network:
    driver: bridge

volumes:
  # Add any persistent volumes here if needed in the future
  stockstream-data:
